version: "3.7"

volumes:
  db:

services:
  postgres-db:
    image: postgres:13-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: maveric_hub
      POSTGRES_like: r_like
      POSTGRES_PASSWORD: r_like@123

  like-service:
    container_name: like-service
    build:
      context: ../like-service
      dockerfile: Dockerfile
    image: like-service:latest
    restart: always
    ports:
      - 4035:4035
    depends_on:
      - postgres-db
    links:
      - postgres-db:database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/maveric_hub
      - SPRING_DATASOURCE_likeNAME=r_like
      - SPRING_DATASOURCE_PASSWORD=r_like@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update